TechAtNYU/intranet

views/index.html
no styling but at least does not allow submission if input is too long, but still allows more input
=> add character counters

app/js/services/form-element-provider.js, app/partials/inputs/number-input.html
Addresses issue #97.
@maxdumas please review, as my angular skillz are non-existent
=> Support numeric inputs

app/js/services/form-element-provider.js
A PR for issue #102. 
@maxdumas sorry if i'm giving you too much to review at once. if you want to do a joint review of any/all of these prs with other people (e.g. with some of our new infra members, or perhaps abhi/cheryl), that could be good—both to make the load lighter for you going forward (so they can review prs) and to onboard them/prepare for when you graduate
=> FormElementProvider: Never give email and url fields a textarea

app/js/controllers/list-ctrl.js, app/partials/actions/list.html
This is my attempt at fixing #85. Again, I have no clue if I'm doing it right, so @maxdumas, please show me the angular wayz.
=> List view: update url on changing selected model

app/index.html, app/js/app.js, app/js/controllers/add-ctrl.js, app/js/controllers/edit-ctrl.js, app/js/controllers/list-ctrl.js, app/partials/actions/add.html, app/partials/actions/edit.html, app/partials/actions/list.html, app/partials/fields/default-field.html, app/partials/index.html, app/partials/inputs/boolean-input.html, app/partials/inputs/date-input.html, app/partials/inputs/default-input.html, app/partials/inputs/enum-input.html, app/partials/inputs/link-input.html, app/partials/inputs/link-multiple-input.html, app/partials/inputs/number-input.html, app/partials/inputs/textarea-input.html, app/partials/inputs/tinymce-input.html
=> Resolve #74 and Add Attribute Compliance

app/js/controllers/edit-ctrl.js, app/js/controllers/inputs/tinymce-ctrl.js, app/partials/actions/list.html, app/partials/inputs/link-input.html, app/partials/inputs/link-multiple-input.html
@grungerabbit @ethanresnick @AbhiAgarwal
=> Resolve #95, #111, #113

app/partials/inputs/boolean-input.html
Closes #116 
ping @maxdumas @AbhiAgarwal please review!
=> Fix boolean inputs

app/index.html
Simple fix that might make it easy for people to edit their profiles for now. @maxdumas
Closes #127
ref https://github.com/TechAtNYU/api/issues/97
=> Changing user.id to me

app/index.html
This resolves a couple console errors in firefox.
=> Fix dependency urls & lack of a charset

app/index.html, app/js/controllers/actions/person/person-add-ctrl.js, app/js/controllers/actions/person/person-edit-ctrl.js, app/js/controllers/actions/person/person-list-ctrl.js, app/js/services/page-provider.js, app/partials/actions/person/person-add.html, app/partials/actions/person/person-edit.html, app/partials/actions/person/person-list.html
• Formatted 'Schools', 'Roles', 'Skills', 'Wants to Learn', 'Wants to Hire'
• 'Image URL' links to the image
• Fixed URL: http://localhost:3000/#/r/people/list/[person-id]
=> List People

app/index.html, app/js/controllers/actions/jobs/jobs-add-ctrl.js, app/js/controllers/actions/jobs/jobs-edit-ctrl.js, app/js/controllers/actions/jobs/jobs-list-ctrl.js, app/js/services/page-provider.js, app/partials/actions/jobs/jobs-add.html, app/partials/actions/jobs/jobs-edit.html, app/partials/actions/jobs/jobs-list.html
search bar includes employer name + position title
data fields populate
html renders
url is linkable
routing works:  .../#/r/jobs/list/[id] >> success!
=> fixed list_jobs

app/index.html, app/js/controllers/actions/incomes/incomes-add-ctrl.js, app/js/controllers/actions/incomes/incomes-edit-ctrl.js, app/js/controllers/actions/incomes/incomes-list-ctrl.js, app/js/services/page-provider.js, app/partials/actions/incomes/incomes-add.html, app/partials/actions/incomes/incomes-edit.html, app/partials/actions/incomes/incomes-list.html
- displayed by shortName, grouped by Month/Year, in descending order (i.e. latest income first)
- unique id link works
- authorizer displays
=> List Income

app/js/controllers/actions/membership/membership-list-ctrl.js, app/partials/actions/membership/membership-list.html
Issue #154
- active and inactive members are grouped
- team leads bubble to the top 🛁
- active members displayed before inactive members
🎉
=> Membership Dropdown

app/index.html, app/js/controllers/actions/reimbursements/reimbursements-add-ctrl.js, app/js/controllers/actions/reimbursements/reimbursements-edit-ctrl.js, app/js/controllers/actions/reimbursements/reimbursements-list-ctrl.js, app/js/services/page-provider.js, app/partials/actions/reimbursements/reimbursements-add.html, app/partials/actions/reimbursements/reimbursements-edit.html, app/partials/actions/reimbursements/reimbursements-list.html
-fixed links
- group by dates
- simplify dates
=> List Reimbursement Requests

app/partials/actions/jobs/jobs-add.html, app/partials/actions/jobs/jobs-edit.html
- disable custom changes in expires-at date in text box
=> add edit jobs

app/partials/inputs/number-input.html
input validation: seat number cannot be less than 1
* I changed the default number input to have min value of 1 – felt that it was reasonable since we don't have inputs with negative values.
=> add edit venue

app/css/app.css, app/index.html, app/partials/actions/default/default-list.html, app/partials/actions/event/event-list.html, app/partials/actions/incomes/incomes-list.html, app/partials/actions/jobs/jobs-add.html, app/partials/actions/jobs/jobs-edit.html, app/partials/actions/jobs/jobs-list.html, app/partials/actions/membership/membership-list.html, app/partials/actions/organization/organization-list.html, app/partials/actions/person/person-list.html, app/partials/actions/reimbursements/reimbursements-list.html, app/partials/actions/venues/venues-list.html, app/partials/fields/default-field.html, app/partials/index.html, app/partials/inputs/boolean-input.html, app/partials/inputs/date-input.html, app/partials/inputs/link-input.html, app/partials/inputs/link-multiple-input.html
Bootstrap 4
---
- Minor facelift, no functional changes
- No more glyphicon, using font awesome instead
- Some changes in class names, nothing breaking
=> Upgrade to Bootstrap 4

app/js/controllers/actions/membership/membership-add-ctrl.js, app/js/controllers/actions/membership/membership-edit-ctrl.js, app/js/controllers/actions/venues/venues-add-ctrl.js, app/js/filters.js, app/partials/actions/membership/membership-add.html, app/partials/actions/membership/membership-edit.html
Position is displayed as **words** not numbers, Lead displayed first
Start and End date text box is read-only
=> Add edit membership

app/partials/actions/membership/membership-add.html, app/partials/actions/membership/membership-edit.html
• upgrade to Bootstrap v4
• Bold some text
• Updated calendar icon and button styles
=> Membership Add & Edit pages: CSS fix

app/js/services/form-element-provider.js, app/partials/actions/venues/venues-add.html
HTML formatting causing people to be unable to add venues
Fixes: https://github.com/TechAtNYU/intranet/issues/125
=> Change venue input to default input

.gitignore, app/js/controllers/actions/event/event-list-ctrl.js, app/js/controllers/actions/expenses/expenses-list-ctrl.js, app/js/controllers/actions/incomes/incomes-list-ctrl.js, app/js/controllers/actions/membership/membership-list-ctrl.js, app/js/controllers/actions/position/position-list-ctrl.js, app/js/controllers/actions/reimbursements/reimbursements-list-ctrl.js, app/js/filters.js, app/js/services/preprocessing.js
• Added Update Selection
• Added Delete Selection
• Converted responsibilities to string, and display none if array is empty.
See Issue #183
=> Fixing bugs on Position Page

app/index.html, app/js/controllers/main-ctrl.js, app/partials/actions/membership/membership-add.html, app/partials/actions/membership/membership-edit.html, app/partials/index.html, app/partials/inputs/link-input.html, app/partials/inputs/link-multiple-input.html
* Now when you click on the resource name, i.e. 'Events', you will be brought to the 'List events' page.
* Switch to using a stable font-awesome version and update relevant icons.
=> Remove 'List' button

.circleci/config.yml
=> CircleCI V2.0 upgrade

.circleci/config.yml
update develop with circle v2 config file (i merged to master without merging to develop by accident)
=> add circle v2 config file (#198)

app/js/app.js
https://github.com/mgonto/restangular#can-i-cache-requests
Caching HTTP requests to prevent too many calls to API to speed things up a bit.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
=> Caching HTTP requests

app/js/controllers/actions/venues/venues-list-ctrl.js
* Added preProcess function for converting time in Venue
=> Added time conversion function to venue controller
